//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contractor()
        {
            this.CookOrders = new HashSet<CookOrder>();
            this.EntireCostPerCompanies = new HashSet<EntireCostPerCompany>();
            this.MidNights = new HashSet<MidNight>();
            this.People = new HashSet<Person>();
            this.Res_Cont_Contract = new HashSet<Res_Cont_Contract>();
            this.Stacks = new HashSet<Stack>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Unit_Id_Fk { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public Nullable<int> Status_Id_Fk { get; set; }
        public Nullable<System.DateTime> PoonehArchived { get; set; }
    
        public virtual SupplierStatu SupplierStatu { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CookOrder> CookOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntireCostPerCompany> EntireCostPerCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MidNight> MidNights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Res_Cont_Contract> Res_Cont_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stack> Stacks { get; set; }
    }
}
