//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMinuteItem
    {
        public int Id { get; set; }
        public Nullable<int> DailyMinute_Id_Fk { get; set; }
        public Nullable<int> Food_Id_Fk { get; set; }
        public Nullable<int> Saloon { get; set; }
        public Nullable<int> MiniRestaurant { get; set; }
        public Nullable<int> TakeAway { get; set; }
        public Nullable<int> Sum { get; set; }
        public string Note { get; set; }
        public Nullable<int> User_Id_Fk { get; set; }
        public string DailyMinuteItemDate { get; set; }
        public Nullable<long> Fee { get; set; }
        public Nullable<long> FeeSum { get; set; }
        public Nullable<int> OverhaulSaloon { get; set; }
        public Nullable<int> OverhaulMiniRestaurant { get; set; }
        public Nullable<int> OverhaulTakeAway { get; set; }
        public Nullable<int> Forecast { get; set; }
        public Nullable<int> Minutes { get; set; }
    
        public virtual DailyMinute DailyMinute { get; set; }
        public virtual Food Food { get; set; }
        public virtual PoonehWebUser PoonehWebUser { get; set; }
    }
}
