//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntireCostPerCompany
    {
        public int Id { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public Nullable<int> Meal_Id_Fk { get; set; }
        public Nullable<int> Contractor_Id_Fk { get; set; }
        public Nullable<long> NormalNo { get; set; }
        public Nullable<long> OverhaulNo { get; set; }
        public Nullable<long> VIPNo { get; set; }
        public Nullable<long> NormalFee { get; set; }
        public Nullable<long> VIPFee { get; set; }
        public Nullable<long> SumNo { get; set; }
        public Nullable<long> SumFee { get; set; }
        public string ECPCDate { get; set; }
        public string FoodName { get; set; }
        public string ECPCMonth { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
