//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuestCard()
        {
            this.GuestGenerals = new HashSet<GuestGeneral>();
        }
    
        public int Id { get; set; }
        public string HexCode { get; set; }
        public string StartDate { get; set; }
        public string ExpireDate { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public string CardName { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestGeneral> GuestGenerals { get; set; }
    }
}
