//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Food_Material = new HashSet<Food_Material>();
            this.StackDocuments = new HashSet<StackDocument>();
            this.StackStocks = new HashSet<StackStock>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaterialType_Id_Fk { get; set; }
        public string Note { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> BigUnit_Id_Fk { get; set; }
        public Nullable<int> SmallUnit_Id_Fk { get; set; }
        public string MaterialCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_Material> Food_Material { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual MeasurementUnit MeasurementUnit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StackDocument> StackDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StackStock> StackStocks { get; set; }
    }
}
