//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MidNight
    {
        public int Id { get; set; }
        public Nullable<int> Person_Id_Fk { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> User_Id_Fk { get; set; }
        public string RegTime { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public Nullable<int> Unit_Id_Fk { get; set; }
        public Nullable<int> Contractor_Id_Fk { get; set; }
        public string MNDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual Person Person { get; set; }
        public virtual PoonehWebUser PoonehWebUser { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
