//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoonehEntities : DbContext
    {
        public PoonehEntities()
            : base("name=PoonehEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<CookOrder> CookOrders { get; set; }
        public virtual DbSet<CookOrderType> CookOrderTypes { get; set; }
        public virtual DbSet<DailyMinute> DailyMinutes { get; set; }
        public virtual DbSet<DailyMinuteDocument> DailyMinuteDocuments { get; set; }
        public virtual DbSet<DailyMinuteItem> DailyMinuteItems { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<EntireCost> EntireCosts { get; set; }
        public virtual DbSet<EntireCostPerCompany> EntireCostPerCompanies { get; set; }
        public virtual DbSet<ExtraTime> ExtraTimes { get; set; }
        public virtual DbSet<Faal> Faals { get; set; }
        public virtual DbSet<Faal_Temp> Faal_Temp { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Food_Material> Food_Material { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<GuestCard> GuestCards { get; set; }
        public virtual DbSet<GuestGeneral> GuestGenerals { get; set; }
        public virtual DbSet<GuestType> GuestTypes { get; set; }
        public virtual DbSet<HelpDesk> HelpDesks { get; set; }
        public virtual DbSet<HelpDeskCategory> HelpDeskCategories { get; set; }
        public virtual DbSet<HoliDay> HoliDays { get; set; }
        public virtual DbSet<IdentifyInfo> IdentifyInfoes { get; set; }
        public virtual DbSet<Kiosk> Kiosks { get; set; }
        public virtual DbSet<KioskApp> KioskApps { get; set; }
        public virtual DbSet<KioskMessage> KioskMessages { get; set; }
        public virtual DbSet<KioskPass> KioskPasses { get; set; }
        public virtual DbSet<KioskRestartTime> KioskRestartTimes { get; set; }
        public virtual DbSet<KioskTimeSetter> KioskTimeSetters { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public virtual DbSet<MidNight> MidNights { get; set; }
        public virtual DbSet<MidNightUnit> MidNightUnits { get; set; }
        public virtual DbSet<PageContent> PageContents { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_IdentifyInfo> Person_IdentifyInfo { get; set; }
        public virtual DbSet<Person_IdentifyInfo_Bup> Person_IdentifyInfo_Bup { get; set; }
        public virtual DbSet<Person_IdentifyInfo_temp> Person_IdentifyInfo_temp { get; set; }
        public virtual DbSet<Person_Meal> Person_Meal { get; set; }
        public virtual DbSet<Person_Restaurant> Person_Restaurant { get; set; }
        public virtual DbSet<Person_Restaurant_1395_03> Person_Restaurant_1395_03 { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<PoonehForm> PoonehForms { get; set; }
        public virtual DbSet<PoonehReservation> PoonehReservations { get; set; }
        public virtual DbSet<PoonehUser> PoonehUsers { get; set; }
        public virtual DbSet<PoonehUser_Form> PoonehUser_Form { get; set; }
        public virtual DbSet<PoonehWebPage> PoonehWebPages { get; set; }
        public virtual DbSet<PoonehWebUser> PoonehWebUsers { get; set; }
        public virtual DbSet<PRTemp> PRTemps { get; set; }
        public virtual DbSet<Res_Cont_Contract> Res_Cont_Contract { get; set; }
        public virtual DbSet<Res_Cont_Contract_Restaurant> Res_Cont_Contract_Restaurant { get; set; }
        public virtual DbSet<Res_Cont_ContractItem> Res_Cont_ContractItem { get; set; }
        public virtual DbSet<ReservationDayCount> ReservationDayCounts { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantContractor> RestaurantContractors { get; set; }
        public virtual DbSet<RestaurantDailyMinute> RestaurantDailyMinutes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Sex> Sexes { get; set; }
        public virtual DbSet<ShiftDate> ShiftDates { get; set; }
        public virtual DbSet<Stack> Stacks { get; set; }
        public virtual DbSet<StackDocument> StackDocuments { get; set; }
        public virtual DbSet<StackDocumentType> StackDocumentTypes { get; set; }
        public virtual DbSet<StackStock> StackStocks { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SupplierStatu> SupplierStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TakeAway> TakeAways { get; set; }
        public virtual DbSet<TakeAwayDetail> TakeAwayDetails { get; set; }
        public virtual DbSet<TakeAwayDocument> TakeAwayDocuments { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<Tray> Trays { get; set; }
        public virtual DbSet<TrayItem> TrayItems { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitCard> UnitCards { get; set; }
        public virtual DbSet<UsedService> UsedServices { get; set; }
        public virtual DbSet<VIPServed> VIPServeds { get; set; }
        public virtual DbSet<WebUser_Page> WebUser_Page { get; set; }
        public virtual DbSet<WorkSheet> WorkSheets { get; set; }
        public virtual DbSet<Schedule13951005> Schedule13951005 { get; set; }
        public virtual DbSet<ScheduleShift> ScheduleShifts { get; set; }
    }
}
