//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public int Id { get; set; }
        public string PageContentBody { get; set; }
        public string PageContentTitle { get; set; }
        public Nullable<int> Page_Id_Fk { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    
        public virtual PoonehWebPage PoonehWebPage { get; set; }
    }
}
