//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Restaurant_1395_03
    {
        public int Id { get; set; }
        public Nullable<int> Person_Id_Fk { get; set; }
        public Nullable<int> Restaurant_Id_Fk { get; set; }
    }
}
