//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoonehUser_Form
    {
        public int Id { get; set; }
        public Nullable<int> Form_Id_Fk { get; set; }
        public Nullable<int> PoonehUser_Id_Fk { get; set; }
    
        public virtual PoonehForm PoonehForm { get; set; }
        public virtual PoonehUser PoonehUser { get; set; }
    }
}
