//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoonehReservation
    {
        public int Id { get; set; }
        public Nullable<int> Tray_Id_Fk { get; set; }
        public Nullable<int> Person_Id_Fk { get; set; }
        public Nullable<int> Schedule_Id_Fk { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public Nullable<int> Unit_Id_Fk { get; set; }
        public Nullable<int> Restaurant_Id_Fk { get; set; }
        public Nullable<int> Meal_Id_Fk { get; set; }
        public Nullable<System.DateTime> PoonehArchived { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual Person Person { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Tray Tray { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
