//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRTemp
    {
        public int Id { get; set; }
        public Nullable<int> person_id_fk { get; set; }
        public Nullable<int> rest_id_fk { get; set; }
    }
}
