//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Cont_ContractItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Res_Cont_ContractItem()
        {
            this.VIPServeds = new HashSet<VIPServed>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Food_Id_Fk { get; set; }
        public Nullable<long> Fee { get; set; }
        public Nullable<long> TotalFee { get; set; }
        public Nullable<int> Res_Cont_Contract_Id_Fk { get; set; }
        public Nullable<int> PorsNo { get; set; }
        public Nullable<int> Remaining { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Res_Cont_Contract Res_Cont_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIPServed> VIPServeds { get; set; }
    }
}
