//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Cont_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Res_Cont_Contract()
        {
            this.CookOrders = new HashSet<CookOrder>();
            this.DailyMinutes = new HashSet<DailyMinute>();
            this.Res_Cont_Contract_Restaurant = new HashSet<Res_Cont_Contract_Restaurant>();
            this.Res_Cont_ContractItem = new HashSet<Res_Cont_ContractItem>();
            this.Schedules = new HashSet<Schedule>();
            this.ShiftDates = new HashSet<ShiftDate>();
            this.VIPServeds = new HashSet<VIPServed>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Contractor_Id_Fk { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> Restaurant_Id_Fk { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CookOrder> CookOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyMinute> DailyMinutes { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Res_Cont_Contract_Restaurant> Res_Cont_Contract_Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Res_Cont_ContractItem> Res_Cont_ContractItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftDate> ShiftDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIPServed> VIPServeds { get; set; }
    }
}
