//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDayCount
    {
        public int Id { get; set; }
        public Nullable<int> Restaurant_Id_Fk { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<System.DateTime> PoonehArchived { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
