//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StackDocument
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public string RegDate { get; set; }
        public string SDDate { get; set; }
        public Nullable<int> SDType_Id_Fk { get; set; }
        public Nullable<int> Reciever_Id_Fk { get; set; }
        public Nullable<int> Deliveryman_Id_Fk { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> Material_Id_Fk { get; set; }
        public Nullable<int> Stack_Id_Fk { get; set; }
        public string SDNo { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Stack Stack { get; set; }
        public virtual StackDocumentType StackDocumentType { get; set; }
    }
}
