//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeAwayDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TakeAwayDetail()
        {
            this.TakeAwayDocuments = new HashSet<TakeAwayDocument>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Lunch { get; set; }
        public Nullable<int> Dinner { get; set; }
        public Nullable<int> MidNight { get; set; }
        public Nullable<int> ExtraMeal { get; set; }
        public Nullable<int> Eftar { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public Nullable<int> TakeAway_Id_Fk { get; set; }
        public string Note { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> User_Id_Fk { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public Nullable<int> Restaurant_Id_Fk { get; set; }
        public Nullable<int> HoliDayLunch { get; set; }
        public Nullable<int> HoliDayDinner { get; set; }
        public Nullable<int> HoliDayMidNight { get; set; }
        public Nullable<int> HoliDayEftar { get; set; }
        public Nullable<int> HoliDayExtraMeal { get; set; }
        public Nullable<int> ThuLunch { get; set; }
        public Nullable<int> ThuDinner { get; set; }
        public Nullable<int> ThuMidNight { get; set; }
        public Nullable<int> ThuEftar { get; set; }
        public Nullable<int> ThuExtraMeal { get; set; }
        public Nullable<int> LunchSecond { get; set; }
        public Nullable<int> LunchThird { get; set; }
        public Nullable<int> DinnerSecond { get; set; }
        public Nullable<int> DinnerThird { get; set; }
        public Nullable<int> MidNightSecond { get; set; }
        public Nullable<int> MidNightThird { get; set; }
        public Nullable<int> ExtraMealSecond { get; set; }
        public Nullable<int> ExtraMealThird { get; set; }
        public Nullable<int> EftarSecond { get; set; }
        public Nullable<int> EftarThird { get; set; }
        public Nullable<int> HoliDayLunchSecond { get; set; }
        public Nullable<int> HoliDayLunchThird { get; set; }
        public Nullable<int> HoliDayDinnerSecond { get; set; }
        public Nullable<int> HoliDayDinnerThird { get; set; }
        public Nullable<int> HoliDayMidNightSecond { get; set; }
        public Nullable<int> HoliDayMidNightThird { get; set; }
        public Nullable<int> HoliDayEftarSecond { get; set; }
        public Nullable<int> HoliDayEftarThird { get; set; }
        public Nullable<int> HoliDayExtraMealSecond { get; set; }
        public Nullable<int> HoliDayExtraMealThird { get; set; }
        public Nullable<int> ThuLunchSecond { get; set; }
        public Nullable<int> ThuLunchThird { get; set; }
        public Nullable<int> ThuDinnerSecond { get; set; }
        public Nullable<int> ThuDinnerThird { get; set; }
        public Nullable<int> ThuMidNightSecond { get; set; }
        public Nullable<int> ThuMidNightThird { get; set; }
        public Nullable<int> ThuEftarSecond { get; set; }
        public Nullable<int> ThuEftarThird { get; set; }
        public Nullable<int> ThuExtraMealSecond { get; set; }
        public Nullable<int> ThuExtraMealThird { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PoonehWebUser PoonehWebUser { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual TakeAway TakeAway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeAwayDocument> TakeAwayDocuments { get; set; }
    }
}
