//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int RowNumber { get; set; }
        public Nullable<int> EventClass { get; set; }
        public string NTUserName { get; set; }
        public string NTDomainName { get; set; }
        public string HostName { get; set; }
        public Nullable<int> ClientProcessID { get; set; }
        public string ApplicationName { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> SPID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> EventSubClass { get; set; }
        public Nullable<int> Success { get; set; }
        public byte[] LoginSid { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<long> EventSequence { get; set; }
        public Nullable<int> IsSystem { get; set; }
        public string SessionLoginName { get; set; }
        public string ServerName { get; set; }
        public string TextData { get; set; }
        public Nullable<int> DatabaseID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Error { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> IndexID { get; set; }
        public Nullable<int> IntegerData { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string ObjectName { get; set; }
        public Nullable<long> XactSequence { get; set; }
        public Nullable<long> BigintData1 { get; set; }
        public Nullable<long> ObjectID2 { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string FileName { get; set; }
        public byte[] BinaryData { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<long> Permissions { get; set; }
        public Nullable<int> NestLevel { get; set; }
        public string OwnerName { get; set; }
        public string TargetUserName { get; set; }
        public string DBUserName { get; set; }
        public string TargetLoginName { get; set; }
        public byte[] TargetLoginSid { get; set; }
        public Nullable<int> ColumnPermissions { get; set; }
        public string ParentName { get; set; }
        public string RoleName { get; set; }
    }
}
