//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservatioan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitCard()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Unit_Id_Fk { get; set; }
        public Nullable<int> Company_Id_Fk { get; set; }
        public Nullable<int> Card_Id_Fk { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<bool> CEnabled { get; set; }
        public string CardName { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
